services:
  spanios-wiki:
    image: crpi-yddandol1embdyi1.cn-shenzhen.personal.cr.aliyuncs.com/waylon_zhang/spanios-wiki:0.0.1
    ports:
      - 3000
    environment:
      - NODE_ENV=${NODE_ENV}
      
    restart: unless-stopped
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true