services:
  api-qdkf-net:
    image: crpi-yddandol1embdyi1.cn-shenzhen.personal.cr.aliyuncs.com/waylon_zhang/api-qdkf-net:latest
    ports:
      - 1337
    environment:
      # 你可以在这里直接设置环境变量
      # 或者在 Dokploy 的界面中配置
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true